markdown: rdiscount
permalink: /:title/
url: http://yvanhe.github.io
highlighter: pygments
name: Yvan's Blog
author: yvanhe
email: yvancoder@gmail.com
duoshuo: yvanhe
hub: yvanhe
safe: true
paginate: 100
about: "还没想好"
