markdown: rdiscount
permalink: /:title/
url: http://yvanhe.github.io
highlighter: pygments
name: Yvan's Blog
description: Yvan's Blog|怕什么真理无穷,进一寸有一寸的欢喜。
author: yvanhe
email: hnns1990@gmail.com
duoshuo: yvanhe
weibo: YvanHe
hub: yvanhe
safe: true
paginate: 100
about: "还没想好"
