markdown: rdiscount
permalink: /:title/
url: http://yvanhe.github.io
highlighter: pygments
name: Yvan's Blog
author: yvanhe
email: yvancoder@gmail.com
duoshuo: yvanhe
hub: yvanhe
hmsrc: //hm.baidu.com/hm.js?674a43d335f655bea8b6062129f59e0e
safe: true
paginate: 100
about: "还没想好"
